name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.410
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --no-restore
    - name: Test
      run: dotnet run --project ./src/OpenDataWorker.COVID19_ScreeningStation
    - uses: EndBug/add-and-commit@v7
      with:
        message: 'Update Covid19 ScreeningStation json file'
      
